apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic-ns
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      # 🔹 여기: service account 지정
      serviceAccountName: petclinic-sa

      nodeSelector:
        role: "app"

      tolerations:
        - key: "role"
          operator: "Equal"
          value: "app"
          effect: "NoSchedule"

      containers:
        - name: petclinic-container
          image: 723926525504.dkr.ecr.ap-northeast-2.amazonaws.com/eks/petclinic:211b94a

          # DB 설정은 ConfigMap / Secret에서 그대로 가져오기
          envFrom:
            - secretRef:
                name: petclinic-db-secret

          # 🔹 여기: Spring profile을 postgres용으로
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "postgres"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"

          ports:
            - name: http
              containerPort: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
